### ISSUE TITLE
FavIcon

### ISSUE THREAD

**Issue by danielbelchior** [MinisterioPublicoRJ/gestao-qualidade-promotoria#19]

**Comment by lucianobarauna** [comment]
Isso já está implementado, qual a problema que tá rolando ?

**Comment by lucianobarauna** [comment]
O caminho estava relativo então bem provável do servidor pegar o favicon do mp, concertei o erro colocando ele como absoluto.
O link ficou assim:
'''
 <link rel="shortcut icon" href="http://apps.mprj.mp.br/sistema/gqp/favicon.ico">
'''
Agora só precisa aplicar o deploy o pull request foi esse aqui #21
